### ISSUE TITLE
Compatibility issues with the macOS system & detailed instructions on building a data-driven atlas

### ISSUE THREAD

**Issue by atlasctlang** [shiveshc/CRF_Cell_ID#1]
Hi. Thanks a lot for the code. It's really helpful but I had a question.
I ran this code on macOS 11.2.3 & Matlab R2020b & no Nvidia GPUs.
The Matlab keeps giving errors like
   ```matlab
   dlopen(./CRF_Cell_ID/UGM/compiled/UGM_makeClampedPotentialsC.mexmaci64, 6):
   Library not loaded: @loader_path/libmex.dylib
   Referenced from: ./CRF_Cell_ID/UGM/compiled/UGM_makeClampedPotentialsC.mexmaci64
     Reason: image not found
   ```
I tried to figure out if something was wrong with my computer, but after I tried almost every solution on the internet, I still couldn't run the code without seeing the error above. Could you please help me with this?

Also, I am really looking forward to the detailed instructions on building a data-driven atlas!

Thank you in advance!

**Comment by shiveshc** [comment]
Hi. Thank you for trying out our method. 

1. The first issue regarding Matlab error seems to be something related to MacOS or mex compilers because we developed and tested our code using Windows OS only. Our method uses graphical models toolbox for Matlab available here https://www.cs.ubc.ca/~schmidtm/Software/UGM.html. Here are couple of things that you could try - 

- Check the supported compilers for Matlab R2020b here https://www.mathworks.com/content/dam/mathworks/mathworks-dot-com/support/sysreq/files/system-requirements-release-2020b-supported-compilers.pdf. See if you have one of these compilers.
- Download the UGM toolbox again from the link provided above. If you do so you may have to update some of the files provided in the Updates section in the above link e.g. "UGM_makeEdgeStruct.m" from 2012 update, "UGM_LoopyBP.m" from 2013 update, "UGM_makeClampedPotentialsC.c" from 2015 update. The last file may be directly relevant to your issue.
- Check if the pre-compiled c/cpp files are available in the UGM folder for "UGM_makeClampedPotentialsC" and try compiling again for MacOS. https://www.mathworks.com/help/matlab/ref/mex.html

2. Regarding the detailed instructions on building data driven atlases, we'll be adding the detailed instructions soon. In the mean time here's a brief description - 

- These files are relevant to building data driven atlas - 'CRF_Cell_ID/utils_NeuroPAL/update_atlas_based_on_annotation.m', 'CRF_Cell_ID/utils_NeuroPAL/compile_annotated_data.m' and 'CRF_Cell_ID/Runs/Run_SyntheticData/data_neuron_relationship.mat'
- The first step in building data driven atlas is load positional relationships in OpenWorm atlas using the file ''CRF_Cell_ID/Runs/Run_SyntheticData/data_neuron_relationship.mat'. This atlas serves as the base atlas i.e. positional relationship among neuron pair is defined from this atlas in the case no experimental data is available for those pair of neurons. For the other pair of neurons for which information is available in annotated data, positional relationship and other features are updated using experimental data.
- Second step is compile all annotated data using the function 'CRF_Cell_ID/utils_NeuroPAL/compile_annotated_data.m'. Please keep in mind the input format of hand annotated files. You can check the typical format in Datasets folder e.g. "CRF_Cell_ID/Datasets/NeuroPAL/1/marker_names.xlsx" and "CRF_Cell_ID/Datasets/NeuroPAL/1/markers"
- Third step is to update the features in OpenWorm atlas using compiled annotated data. This is done in the function 'CRF_Cell_ID/utils_NeuroPAL/update_atlas_based_on_annotation.m'

Above steps are sufficient to build data-driven positional relationship atlases. We'll be adding instructions on how to build color data-driven color atlases soon too.
Hope you find this helpful and feel free to reach out if your issue gets resolved.
